services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - questdb
    networks:
      - grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_RENDERING_TOKEN=0505e1a5b1847cde53b25f3892335950

  renderer:
    container_name: renderer
    image: grafana/grafana-image-renderer:latest
    restart: unless-stopped
    networks:
      - grafana
    environment:
      - RENDERING_AUTH_TOKEN=0505e1a5b1847cde53b25f3892335950

  questdb:
    container_name: questdb
    image: questdb/questdb:latest
    networks:
      - grafana
    ports:
      - "127.0.0.1:9000:9000" # REST API and Web UI
      - "127.0.0.1:8812:8812" # TCP Postgres
    restart: unless-stopped
    volumes:
      - questdb_data:/var/lib/questdb

volumes:
  grafana-storage:
    external: true
  questdb_data:
    external: true
networks:
  grafana:
    name: grafana
