services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - questdb
    networks:
      - grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=https://github.com/performancecopilot/grafana-pcp/releases/download/v5.1.1/performancecopilot-pcp-app-5.1.1.zip;performancecopilot-pcp-app

  questdb:
      container_name: questdb
      image: questdb/questdb:latest
      networks:
        - grafana
      ports:
        - "127.0.0.1:9000:9000" # REST API and Web UI
      #  - "127.0.0.1:8812:8812" # TCP Postgres
      restart: unless-stopped
      volumes:
        - questdb_data:/var/lib/questdb

volumes:
  grafana-storage:
    external: true
  questdb_data:
    external: true
networks:
  grafana:
    name: grafana
